# fly.toml app configuration file generated for ai-blog-writer-api on 2024-01-27T12:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "ai-blog-writer-api"
primary_region = "iad"

[build]
  dockerfile = "apps/gateway/Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/v1/health"

[machine]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[metrics]
  port = 9091
  path = "/metrics"

[deploy]
  release_command = "npm run migrate"

[experimental]
  enable_consul = true

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
