apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ai-blog-writer
type: Opaque
data:
  host: <base64-encoded-db-host>
  port: <base64-encoded-db-port>
  name: <base64-encoded-db-name>
  user: <base64-encoded-db-user>
  password: <base64-encoded-db-password>

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: ai-blog-writer
type: Opaque
data:
  host: <base64-encoded-redis-host>
  port: <base64-encoded-redis-port>
  password: <base64-encoded-redis-password>

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: ai-blog-writer
type: Opaque
data:
  secret: <base64-encoded-jwt-secret>

---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: ai-blog-writer
type: Opaque
data:
  key: <base64-encoded-openai-api-key>

---
apiVersion: v1
kind: Secret
metadata:
  name: anthropic-secret
  namespace: ai-blog-writer
type: Opaque
data:
  key: <base64-encoded-anthropic-api-key>

---
apiVersion: v1
kind: Secret
metadata:
  name: serpapi-secret
  namespace: ai-blog-writer
type: Opaque
data:
  key: <base64-encoded-serpapi-key>

---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: ai-blog-writer
type: Opaque
data:
  access-key: <base64-encoded-s3-access-key>
  secret-key: <base64-encoded-s3-secret-key>
  bucket: <base64-encoded-s3-bucket>
  region: <base64-encoded-s3-region>

---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
  namespace: ai-blog-writer
type: Opaque
data:
  secret-key: <base64-encoded-stripe-secret-key>
  webhook-secret: <base64-encoded-stripe-webhook-secret>

---
apiVersion: v1
kind: Secret
metadata:
  name: sentry-secret
  namespace: ai-blog-writer
type: Opaque
data:
  dsn: <base64-encoded-sentry-dsn>
  org: <base64-encoded-sentry-org>
  project: <base64-encoded-sentry-project>
  auth-token: <base64-encoded-sentry-auth-token>
